module.exports = [
    {type:'antiseptic'},
    {type:'respiratory support'},
    {type:'carminative'},
    {type:'antimicrobial'},
    {type:'diuretic'},
    {type:'anti-spasmodic'},
    {type:'liver restorative'},
    {type:'antioxidant'},
    {type:'anti-inflammatory'},
    {type:'analgesic'},
    {type:'calming nervine'},
    {type:'cooling diaphoretic'},
    {type:'expectorant'},
    {type:'liver and gallbladder stimulant'},
    {type:'diuretic'},
    {type:'antidepressant'},
    {type:'fights parasites and intestinal worms'},
    {type:'digestive aid'},
    {type:'antibacterial'},
    {type:'sleep aid'},
    {type:'oral health'},
    {type:'appetitie stimulant'},
    {type:'cholesterol aid'},
    {type:'brain function'},
    {type:'skin health'}
];